#!/usr/bin/env bash
#
# Bump every version literal in the repo to a new release and verify the
# tree still builds and tests cleanly. Stops short of git commit/tag/push
# so the maintainer can review the diff before anything irreversible
# leaves the local machine.
#
# Usage:  scripts/release.sh <new-version>
# Example: scripts/release.sh 0.2.0

set -euo pipefail

if [[ $# -ne 1 ]]; then
    echo "usage: $0 <new-version>" >&2
    echo "       new-version is X.Y.Z (no leading 'v')" >&2
    exit 2
fi

new=$1

if [[ ! $new =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
    echo "error: version must be X.Y.Z (no leading 'v'); got '$new'" >&2
    exit 2
fi

# Run from repo root so paths are stable regardless of where the user invoked.
repo_root=$(git rev-parse --show-toplevel 2>/dev/null) || {
    echo "error: not inside a git repository" >&2
    exit 2
}
cd "$repo_root"

# Refuse to bump on a dirty tree — the diff that follows would be tangled
# with whatever else was in flight.
if ! git diff --quiet || ! git diff --cached --quiet; then
    echo "error: working tree has uncommitted changes; commit or stash first" >&2
    exit 2
fi

current=$(grep -E '^version = ' Cargo.toml | head -1 | sed -E 's/^version = "([^"]+)".*/\1/')
if [[ -z $current ]]; then
    echo "error: could not parse current version from Cargo.toml" >&2
    exit 2
fi
if [[ $new == "$current" ]]; then
    echo "error: $new is the same as the current version" >&2
    exit 2
fi

echo "bumping $current -> $new"

# Three version literals live in the tree. Cargo.lock is regenerated by
# the cargo build below. We use perl -i because BSD and GNU sed disagree
# on the in-place flag (`-i ''` vs `-i`); perl is identical on both.
# \Q...\E quotes the captured version so dots don't act as regex wildcards.
perl -i -pe "s/^version = \"\\Q${current}\\E\"\$/version = \"${new}\"/" Cargo.toml
perl -i -pe "s/set -l expected \\Q${current}\\E\$/set -l expected ${new}/" functions/_angler_install.fish
perl -i -pe "s/--tag v\\Q${current}\\E\\b/--tag v${new}/g" README.md

# Regenerate Cargo.lock and verify the bumped version compiles.
cargo build --quiet

echo
echo "--- changed files ---"
git diff --stat

# Full test sweep — catches regressions and confirms the bumped version
# parses through fmt + clippy + tests.
echo
echo "--- make check ---"
if ! make check; then
    echo >&2
    echo "error: make check failed; release aborted (no commit made)" >&2
    exit 1
fi

echo
echo "--- next steps ---"
echo "  review:  git diff"
echo "  commit:  git commit -am \"Release v${new}\""
echo "  tag:     git tag -a v${new} -m \"v${new}\""
echo "  push:    git push && git push origin v${new}"
echo
echo "the release workflow runs on tag push and produces tarballs at"
echo "  https://github.com/tymcauley/angler/releases/tag/v${new}"
